[package]
authors = ["Yuriy Larin"]
name = "rust_random_exercises"
version = "0.0.1"
readme = "README.MD"
license = "Apache"
repository = "git@github.com:blandger/rust_random_exercises.git"
edition = "2024"

[dependencies]
